_target_: evals.datasets.taskonomy.Taskonomy
snorm_path: uva-cv-lab/taskonomy_snorm_seg
other_path: uva-cv-lab/taskonomy_seg
image_mean: imagenet
augment_train: True
center_crop: True
task: principal_curvature
name: taskonomy