system:
  random_seed: 8
  num_gpus: 2
  port: 12355
note: ""
batch_size: 16
wandb:
  use: True
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: nyu
  - probe: depth_dpt
  - _self_
experiment_name: SSL_Depth_Probing
experiment_model: dinov2_b14
is_eval: False
ckpt_path: ""
output_dir: "result"
