system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
batch_size: 16
wandb:
  use: True
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: twoafcdataset
  - probe: depth_dpt
  - _self_
experiment_name: SSL_Model_Percepture
experiment_model: dinov2_b14
output_dir: "result"