random_seed: 8
scale_factor: 0.25
num_corr: 1000
multilayer: False
defaults:
  - dataset: navi
output_dir: /p/openvocabdustr/probing_midlevel_vision/code/probing-mid-level-vision/result/correspondance
model_name: dino_b16